### ISSUE TITLE
Error: Method Illuminate\Database\Query\Builder::customers does not exist. 

### ISSUE THREAD

**Issue by learn2develop** [vanilophp/demo#10]
I am trying to insert address for a company and this error comes up above the form:
Error: Method Illuminate\Database\Query\Builder::customers does not exist.

The address gets inserted, however there is no link created between customer to address in customer_addresses table.

this is where the exception is thrown
/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php line 2817

originating from
vendor/konekt/appshell/src/Http/Controllers/AddressController.php method store()

Any help on this please?

**Comment by fulopattila122** [comment]
Thank you for the report!

I've found what's causing the bug. I'm not yet sure which way to fix it (kind of a chicken & egg problem), but will fix it by tomorrow afternoon and will let you know once it's out.

**Comment by fulopattila122** [comment]
This issue will be fixed in v0.4 which will be released on 27th October 2018 (tomorrow).
The bug will not be fixed in v0.3 and the create address functionality in Admin will not work for that version.

Related to vanilophp/framework#25

**Comment by learn2develop** [comment]
Thank you help
