### ISSUE TITLE
Installation - Demo Shop

### ISSUE THREAD

**Issue by jonathan-martz** [vanilophp/demo#103]
I followed the docs at https://vanilo.io/docs/3.x/installation and installed vanillo, but i only can see the default Laravel welcome screen.

I did not the steps of *Laravel Auth Support*:

Is there anything missing ? Looks like a Provider for the routes is missing. Any Idea ?
https://www.kerntopp.shop/

https://www.kerntopp.shop/login
is working, but without styles.

https://www.kerntopp.shop/home
Home as well.

**Comment by fulopattila122** [comment]
This demo repository is a demo shop that you can download and install as a ready-made/prepared Laravel application.
This demo contains a possible implementation of a shop with Vanilo.

Vanilo is a framework and - similarly to Laravel - it can be used in arbitrary ways.  The installation docs you're referring to is covering the installation of Vanilo to an entirely new application (or adding it to an existing one).

Therefore, this demo repo is a sample implementation. Refer to the code in this repo for further inspiration.
