### ISSUE TITLE
Class "Konekt\AppShell\Providers\ModuleServiceProvider" not found

### ISSUE THREAD

**Issue by Rub-s** [vanilophp/demo#108]
Hello,

I get this error when running `composer install`

error : 
**Class "Konekt\AppShell\Providers\ModuleServiceProvider" not found**
**Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1**

**Comment by fulopattila122** [comment]
Which branch did you use? What is your PHP version? Any other error message before the given error message?

**Comment by Rub-s** [comment]
I was installing with php -v 8.1 😅
I was changing php version in composer.json.
I now installed the demo with php -v 7.4 and **it works like a charm** 😀

Big props for your work man. And thank you for your quick response.

**Comment by fulopattila122** [comment]
The master branch of this repo is bound to Vanilo 3.x but I have to admit that it's lagging quite a lot behind the latest changes of the framework.

Probably this will get a major update by November, but I can't promise :angel:
