### ISSUE TITLE
Master product demo

### ISSUE THREAD

**Issue by mihaisolomon** [vanilophp/demo#113]
Hey,

I installed the demo application I added a master product with variants but could not see it in the frontend. Any idea how I can see it? Or it's not available in the demo?

**Comment by fulopattila122** [comment]
Salut Mihai,

The issue is not on your end, currently the ProductFinder doesn't retrieve master products.
The fix is coming this week.

Are you using MySQL or some other DB engine?
Because for MySQL there's a relatively quick fix.

**Comment by mihaisolomon** [comment]
I'm using MariaDb Mysql.

**Comment by fulopattila122** [comment]
Yes, MariaDB works as well, of course :)

**Comment by fulopattila122** [comment]
Do you plan to use both normal products or only master/variants?

**Comment by mihaisolomon** [comment]
I have both. I would prefer to use both if it's posible.
From what I saw it's either simple or master product, correct?

**Comment by mihaisolomon** [comment]
Hey,

Do you have an answer for me?

**Comment by fulopattila122** [comment]
Hey Mihai,

sorry for the slow response. The good news is that it works now, regardless of the DB engine.

With the fresh Vanilo v3.7 release, the new `ProductSearch` class has been added that is a drop-in replacement of the former `ProductFinder` class. The most important difference between the two is that `ProductSearch` works with both simple products and masters products as well.

This demo repository has been updated accordingly. Please pull the latest version that is capable of handling this situation.
Most of the changes have happened in this commit 5cc97293f7c27690a9bb55b2e3a3011e0db5451f
