### ISSUE TITLE
Not able to see shop main menu

### ISSUE THREAD

**Issue by arunjoseph02** [vanilophp/demo#114]
Hi I was trying my hand on Vanilo admin application, I followed as it in the documentation and also took the demo I am not able to see the shop drop down menu but in the screenshot I can see the shop main menu, please help in regards with the same. I am using 

vanilo/admin - 3.0
vanilo/framework - 3.1

Am I missing anything here?
Please help
<img width="1766" alt="Screenshot 2023-04-10 at 4 21 11 PM" src="https://user-images.githubusercontent.com/115861577/230888130-f30ec087-42da-438d-8324-a178381d148e.png">

**Comment by fulopattila122** [comment]
Did you add the module to concord.php?

**Comment by fulopattila122** [comment]
What is the output of `php artisan concord:modules -a`?

**Comment by arunjoseph02** [comment]
This is the output of the above command

<img width="861" alt="Screenshot 2023-04-11 at 6 58 09 AM" src="https://user-images.githubusercontent.com/115861577/231031591-638152ca-48ac-4c62-a999-f4229cd3f041.png">

AppServiceProvider
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Konekt\Menu\Facades\Menu;


class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->app->concord->registerModel(\Konekt\User\Contracts\User::class, \App\Models\User::class);
        if ($menu = Menu::get('appshell')) {
            // $menu->addItem('sales', __('Sales')); // <- New root level header
            // $menu->addItem('product', __('Product'), ['route' => 'vanilo.product'])->data('icon', 'product')->allowIfUserCan('list product');
            // $menu->addItem('funnels', __('Funnels'),
            //     ['route' => 'app.funnel.index'])
            //      ->data('icon', 'funnels')
            //      ->allowIfUserCan('list funnels');

            $stats = $menu->addItem('stats', __('Statistics')); // Root level group
            $stats->allowIfUserCan('view monthly revenues');

            // Add an item in the stats group
            // $stats->addSubItem('monthly_revenue', __('Monthly Revenue'), ['route' => 'statistics.monthly_revenue.index'])
            //       ->data('icon', 'chart')
            //       ->activateOnUrls('/statistics/monthly_revenue/*')
            //       ->allowIfUserCan('view monthly revenues');
        }
    }
}
```

Also it is laravel 10 that I am using, is that causing any trouble ?

**Comment by arunjoseph02** [comment]
Ok thanks a lot @fulopattila122 is there any work around for this ? For the time being? 

The above snippet I got it from one of your links from the documentation

**Comment by fulopattila122** [comment]
What is the output of this command if you run it from your application's root folder?

```bash
php -r 'require "vendor/autoload.php";$c=require "config/concord.php";foreach ($c["modules"] as $key=>$val) {echo "$key: " . (is_array($val) ? "array" : $val) . "\n";}'
```

**Comment by fulopattila122** [comment]
Another tip: try running migrations.

If it doesn't help, please show me what do you see on the page in the Settings -> Permissions -> "admin" role

**Comment by fulopattila122** [comment]
Also, what is the output of this:

```bash
composer show vanilo/admin|head -11
```
?

**Comment by arunjoseph02** [comment]
Hi @fulopattila122 I need to still try it I am currently out and not able to access my workstation I will try these steps once I am back to my workstation thank you for the help

**Comment by arunjoseph02** [comment]
@fulopattila122 it worked after doing migrations
