### ISSUE TITLE
Dropdown Menus Not Functioning

### ISSUE THREAD

**Issue by kamilkozak** [vanilophp/demo#118]
Hi,

I've encountered an issue with the dropdown menus; they are not expanding when clicked.

Screenshot:
![image](https://github.com/user-attachments/assets/e5f685d7-103f-4e9b-9c7e-c83c1e5042bf)

Steps to reproduce:

Go to the page with the dropdowns.
Click on any dropdown menu.
Observe that the dropdown does not expand.
Expected: The dropdown should expand and display options.
Actual: Nothing happens on click.

Thanks!

**Comment by nuovo10** [comment]
Hello
Have you been able to fix the error?
Regards

**Comment by fulopattila122** [comment]
> Hello Have you been able to fix the error? Regards

Do you get any errors in the Browser's console?

**Comment by nuovo10** [comment]
hello,
 any errors

**Comment by fulopattila122** [comment]
in the browser's

**Comment by nuovo10** [comment]
There are no errors in the browser

**Comment by fulopattila122** [comment]
Took a while, but it got solved :sweat_smile: 

Please update to the latest master, or, alternatively, apply [these changes](https://github.com/vanilophp/demo/commit/c86d359e07792595bc47a9123fd5500f4d86efa5) to your codebase.

**Comment by nuovo10** [comment]
Thanks!!
