### ISSUE TITLE
Can't login user after updating user in the admin panel

### ISSUE THREAD

**Issue by learn2develop** [vanilophp/demo#12]
I am having issues login in a user after the following steps:

1. created new role "analyst"
2. assigned permissions to the role "list orders, ..., etc."
3. created new user "john.doe@a.com"
3.1 assign user as "admin" and assigned user to the newly created "analyst" role 
4. logged off admin
5. attempted to login "john.doe@a.com" and a message comes up "These credentials do not match our records."
Even if I remove the users role and change him back to clients, the user cannot login.

Any help please?

**Comment by learn2develop** [comment]
Also I have cloned from the "master" branch

**Comment by learn2develop** [comment]
Figured it out, the problem appear when editing the user in the admin panel. The form for editing a user contains a field for password, not supplying password to the password field and saving it changes users password.

**Comment by learn2develop** [comment]
AppShell UserController@update method
the line check for the existence of the password in the request which it does exists but it is empty.

```php
if ($request->has('password') && !empty($request->input('password')))
```

**Comment by fulopattila122** [comment]
> Preface: Please use the "stable" (0.3, 0.4 ...) versions of this repo.
> Everything in master is being heavily modified and possibly contains broken and/or non-integrated code

Fortunately, this bug was fixed ~2-3 days ago.
What's the output of this command: `composer show konekt/appshell|grep versions` ?

Pulling the latest version of this repository and running `composer install` should solve the problem

**Comment by learn2develop** [comment]
I have downloaded the demo more than a week ago
```composer show konekt/appshell|grep versions``` outputs versions : * 0.9.10
```composer install```Nothing to install or update

I redirected the route to a controller that overrides the ```\Konekt\AppShell\Http\Controllers\UserController``` for now.

**Comment by fulopattila122** [comment]
Please run `composer update konekt/appshell`. That will solve the problem.

**Comment by fulopattila122** [comment]
Did the composer update thingy solve the problem?

**Comment by learn2develop** [comment]
It says the same thing "Nothing to install or update".
![image](https://user-images.githubusercontent.com/6439903/48014598-eb6f2b80-e11e-11e8-884f-e0dc3de9c59a.png)

I have tried to run ```composer require konekt/appshell``` but it throws errors.
![image](https://user-images.githubusercontent.com/6439903/48014641-080b6380-e11f-11e8-8b4f-a21b426a51ac.png)

**Comment by fulopattila122** [comment]
True, gears needs to be updated as well.
Please run: `composer update konekt/appshell konekt/gears`
and let me know the results.

Thanks

**Comment by learn2develop** [comment]
running ```composer update konekt/appshell konekt/gears```
output:
![image](https://user-images.githubusercontent.com/6439903/48016637-04c6a680-e124-11e8-8e54-0e4b5bafcf3c.png)

**Comment by fulopattila122** [comment]
Looks better. What does `composer show konekt/appshell|grep versions` give?

**Comment by learn2develop** [comment]
```composer show konekt/appshell|grep versions``` outputs: versions : * 0.9.10

**Comment by fulopattila122** [comment]
It has to be minimum 1.0.0 (latest is 1.1.0).

Either download the latest vanilo/demo (`master` branch) where composer.lock is already on the latest version, or manage to update AppShell with `composer update konekt/appshell`.

As soon as `composer show konekt/appshell|grep versions` gives you at least 1.0.0, then the bug is gone.

**Comment by learn2develop** [comment]
Ok, great I will, thank you for help
