### ISSUE TITLE
It is unsafe to run Dusk in production

### ISSUE THREAD

**Issue by tyrog07** [vanilophp/demo#15]
i am getting these when trying to run artisan commands please help

**Comment by fulopattila122** [comment]
Could you please provide with more Information please?

**Comment by tyrog07** [comment]
F:\xampp_new\htdocs\vanilo_demo\demo>php artisan serve

In DuskServiceProvider.php line 43:

  It is unsafe to run Dusk in production.


this is what i am getting in cmd

**Comment by InstantProgramming** [comment]
Just delete .env.dusk.local.example and rename .env.exemple to => .env and run "php artisan key:generate" to console.

**Comment by pedroreartes** [comment]
you must to set the .env file first
