### ISSUE TITLE
Error en php artisan migrate --seed estoy usando MySql

### ISSUE THREAD

**Issue by cfrisly** [vanilophp/demo#16]
me muestra el siguiente error:

  Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

  at /home/frisly/larapro/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      /home/frisly/larapro/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /home/frisly/larapro/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  Please use the argument -v to see more details.

**Comment by fulopattila122** [comment]
This is a well known Laravel problem: https://laravel-news.com/laravel-5-4-key-too-long-error

But they key length [was set](https://github.com/vanilophp/demo/blob/0.4/app/Providers/AppServiceProvider.php#L17) in this demo project, so I guess you're using the Vanilo framework in an application and you have to add:

```php
Schema::defaultStringLength(191);
```
in your `AppServiceProvider::boot()` method.

**Comment by fulopattila122** [comment]
The [doc](https://vanilo.io/docs/master/installation) says: 

> Database engine: MySQL 5.7 or higher, MariaDB 10.2.7 or higher or PostgreSQL is required

You can check your db engine version with this command:
mysql -V (MySQL and MariaDB)
or
psql - V (Postgres)

**Comment by fulopattila122** [comment]
Has the issue been resolved?

**Comment by fulopattila122** [comment]
Feel free to reopen if the issue persists.
