### ISSUE TITLE
Product Image Won't Show

### ISSUE THREAD

**Issue by joeprabawa** [vanilophp/demo#17]
Hi, i got this issue after upload the product image. I've opened up the console
and it showing this error message : 
**GET** http://127.0.0.1:8000/storage/2/conversions/01-thumbnail.jpg 404 (Not Found)

![screencapture-localhost-8000-admin-product-2019-01-01-18_58_28](https://user-images.githubusercontent.com/33862534/50572282-7dca3d80-0df7-11e9-9f2f-d07d004ae4b7.png)

The preview image didn't showed up, both from the admin panel and from the client
Need a guide to fix this problem. Thank you so much in advance :)

**Comment by fulopattila122** [comment]
You have to run `php artisan storage:link`

https://laravel.com/docs/5.7/filesystem#the-public-disk

**Comment by fulopattila122** [comment]
Did it solve the problem?

**Comment by cfrisly** [comment]
I also have a similar problem with the images does not show them in admin and the store if I have the storage folder

**Comment by fulopattila122** [comment]
Did you try `php artisan storage:link`?

**Comment by fulopattila122** [comment]
Generally it's not a Vanilo but a filesystem/permission problem, but I'll try to help.
What answer do you get when you right click the broken image and click open in new tab? Is it 404 or 403?
What do you see in your log files at the same time?
How do you run your web server, via `php artisan serve` or via nginx or apache maybe homestead or docker?
Does the user running the web server have permission read from those folders?

**Comment by joeprabawa** [comment]
@fulopattila122 thank you so much for the help.

1. it's 404 with this url http://127.0.0.1:8000/storage/3/01.jpg
2. On the console it says GET http://127.0.0.1:8000/storage/3/conversions/01-thumbnail.jpg 404 (Not Found) with error on 
3 & 4. I use `php artisan serve` with basic phpmyadmin root config
5. Applied to all images

**Comment by fulopattila122** [comment]
What's the output of
```bash
stat public/storage
```
?

**Comment by fulopattila122** [comment]
Windows 😶

The problem is that Laravel saves the file into `storage/app/framework/public`, whereas `public/storage` should be a symlink to `../storage/app/public` but as far as I see it's a regular file.

It should be like this:
```
fulop@asus-UX303LA  vanilo/demo   master  stat public/storage 
  File: public/storage -> ../storage/app/public
  Size: 21        	Blocks: 0          IO Block: 4096   symbolic link
Device: 802h/2050d	Inode: 7082242     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/   fulop)   Gid: ( 1000/   fulop)
Access: 2019-01-03 12:20:50.283873521 +0100
Modify: 2018-06-26 22:07:59.484280669 +0200
Change: 2018-06-26 22:07:59.484280669 +0200
 Birth: -
```

Windows symlinks are out of my expertise, so I suggest to take a look at these issues:
https://github.com/laravel/framework/issues/15439
https://github.com/spatie/laravel-medialibrary/issues/1275

**Comment by fulopattila122** [comment]
:bulb: my last tip: you may try to delete `public/storage` (only if it's empty) and run `php artisan storage:link` again.

**Comment by joeprabawa** [comment]
Thanks for refrenced the issue ont the spatie @fulopattila122, i red the comments and yes ! i already did your method a moment ago, it works ! :smile: 

thank you so much for your help !!!  Vanilo Rocks

**Comment by fulopattila122** [comment]
Cool to hear! rock&roll ;) 🤘

**Comment by allawliet** [comment]
Hye, i have tried delete the storage and run the command again but still not working..can someone help me..

**Comment by fulopattila122** [comment]
@allawliet

**Comment by allawliet** [comment]
it show the same as you show

![my](https://user-images.githubusercontent.com/28880477/60248092-7e4e1780-98f4-11e9-802e-76c9d8477495.PNG)

**Comment by allawliet** [comment]
and i am windows  hahaha

**Comment by fulopattila122** [comment]
What does the Browser give you when you try to open the image directly?
(Right click the broken image and "Open Image in new Tab")
404 or 403, or ...?
Also what do you see in your logs?

**Comment by allawliet** [comment]
the error is 404 and there is nothing in my logs
![my2](https://user-images.githubusercontent.com/28880477/60252912-b443c980-98fd-11e9-98f2-34ec6c0e3c3b.PNG)

**Comment by fulopattila122** [comment]
What is the URL of the broken image?

**Comment by allawliet** [comment]
http://localhost/storage/6/conversions/B37705_01-thumbnail.jpg

**Comment by allawliet** [comment]
Hye...i got it..i change the APP_URL and thank god its working =)
Thank you for your help !!

**Comment by fulopattila122** [comment]
Exactly :)

**Comment by Niz47** [comment]
> 
> 
> Hye...i got it..i change the APP_URL and thank god its working =)
> Thank you for your help !!

Hey man, you saved my time. Thanks a million :)
