### ISSUE TITLE
add "notes" field of Order at Checkout form

### ISSUE THREAD

**Issue by mironcat** [vanilophp/demo#18]
How to add "Notes" field of Order at Checkout form?
I see this field at model of Order but I have no idea how fill it at checkout. It is possible?
Thank you in advance!

**Comment by fulopattila122** [comment]
It can be done with v0.5 as well, but the idiomatic solution hasn't been implemented yet and I will push it into v1.0 - which is around the corner anyways

**Comment by mironcat** [comment]
well, I hope v0.5 happens soon!

**Comment by fulopattila122** [comment]
Fixed in v2.0.0
