### ISSUE TITLE
product image not displayed

### ISSUE THREAD

**Issue by JayJoshi18** [vanilophp/demo#22]
I tried uploading both the images it is still not working. I tried both the solutions from #17 and #19 both. 
I tried to change but nothing happened
Also did you artisan storage:link
i run this command and tried changing base url nothing changed

here is the output of stat public/storage 
![Capture](https://user-images.githubusercontent.com/53005732/66585863-3ef6be80-eba5-11e9-9c7b-db5457764bcc.PNG)

Please help ..Thank you so much in advance

**Comment by fulopattila122** [comment]
I'm not 100% sure if symlinks work impeccably on Windows as well.
What is the exact error you get when you try to open the image link directly in your browser?

**Comment by JayJoshi18** [comment]
![image](https://user-images.githubusercontent.com/53005732/66635288-85dbc700-ec2c-11e9-9f77-1d7c9b35d299.png)

**Comment by fulopattila122** [comment]
Can you please copy/paste the full URL of the Admin Dashboard from the browser here?

**Comment by JayJoshi18** [comment]
![image](https://user-images.githubusercontent.com/53005732/66654286-89d10e80-ec57-11e9-8182-d943bd22dcba.png)

**Comment by fulopattila122** [comment]
Set `APP_URL=http://127.0.0.1:8000` in your `.env` file.

It's the same issue as #17
