### ISSUE TITLE
Call to undefined function str_singular() 

### ISSUE THREAD

**Issue by mebtex** [vanilophp/demo#38]
Hi, I installed the demo application, and after adding a new category I get an error when I try to go along the route: 

`admin/taxonomy/{id}`

`Call to undefined function str_singular() (View: patch/vendor/vanilo/framework/src/resources/views/taxonomy/show.blade.php)`

**Comment by fulopattila122** [comment]
Yep, vanilo/framework needs to be dumped to v1.0.1. I do it right now

**Comment by fulopattila122** [comment]
Thanks for the report, it [has been fixed](https://github.com/vanilophp/demo/commit/329af7370a39e8fdb1663b8d0dcdfd37b0514776), please pull latest version either from master or branch `1.x`
