### ISSUE TITLE
Admin section log-in credentials

### ISSUE THREAD

**Issue by mark-stopka** [vanilophp/demo#4]
Hi, is it possible to log-in into the admin section of the [online demo](https://shop.laracom.net/admin/login) or do I have to run my own local instance for that?

**Comment by fulopattila122** [comment]
Hello Mark,

The Laracom site you've linked is another project, not ours, so I don't know how to log in there.
I suggest to submit an issue in their github repo: https://github.com/Laracommerce/laracom

**Comment by mark-stopka** [comment]
Oh yeah, sorry for that, I have been checking way too many Laravel based e-commerce solutions...
