### ISSUE TITLE
Picture doesn't show at shop catalog or product page in admin

### ISSUE THREAD

**Issue by fkolondam** [vanilophp/demo#41]
Pls help me, just installed the demo app, trying to add product with picture, product added with image uploaded, but it doesn't appear at img section everywhere. Looks like there's something trouble with the path

![image](https://user-images.githubusercontent.com/20502226/72189044-c9fe8380-3436-11ea-8fc4-f3c450de3075.png)

**Comment by fulopattila122** [comment]
Hi Franky,

Please look at issues #17 and #22 for the solution.

**Comment by fkolondam** [comment]
> Hi Franky,
> 
> Please look at issues #17 and #22 for the solution.

ohhh thank you, solved.
