### ISSUE TITLE
Multi-language and multi-tenancy support?

### ISSUE THREAD

**Issue by noelc10** [vanilophp/demo#44]
Is there any way on this framework to manage the app with multi-language via the settings page to change overall app language and multi-tenancy approach? Because I think this will end up using a third-party package and make the app size bloated.

Hoping for the response.

Thanks and Good day.

**Comment by fulopattila122** [comment]
Multi-language is going to be supported at a later point ([planned for v2.3](https://vanilo.io/docs/master/roadmap#23-diversity))

Multi-tenancy is not in the scope of Vanilo.
We've been using https://tenancy.samuelstancl.me/ and Vanilo together to build a multi-tenant shop.

An alternative Laravel multi-tenancy package is https://tenancy.dev/, but there are quite few other out there

**Comment by noelc10** [comment]
I see, I hope you release as soon as possible.

Thanks.
