### ISSUE TITLE
getThumbnailUrl on cart page not returning the image. 

### ISSUE THREAD

**Issue by daniel-farina** [vanilophp/demo#46]
Hello everyone, 

For some reason the following is not returning a thumbnail:

```
{{ $item->product->getThumbnailUrl() ?: '/images/product.jpg' }}
```
resources/views/cart/show.blade.php

it works fine on the product and category page with:
```
{{ $product->getThumbnailUrl() }}
```

I also tried:
```
  @if($item->product->hasImage())
 YES:: {{$item->product->getThumbnailUrl() }}
@else
NO IMAGE
@endif
```
and I can confirm it returns no image. 

Is this a known issue?, I'll keep on trying to figure it out and post an update if I find anything.  Any help is appreciated!

Thanks

**Comment by fulopattila122** [comment]
What does `$item->product->getThumbnailUrl()` exactly return? `NULL` or some broken URL?

**Comment by daniel-farina** [comment]
In my case it would return the default:

```
<img src="/images/product.jpg" class="product-image">
```
i will try with a fresh installation soon to discard any changes I made first and test it on a fresh installation.  I'll update this once I figure  it out.

**Comment by daniel-farina** [comment]
@fulopattila122 
If you do the following on the CartController on the show method, does it it return false to you?

```
    public function show()
    {
       $item = Cart::getItems()->first();
        dd($item->product->hasImage());
        
        return view('cart.show');
    }
```

Mine returns false, even though the item does have images . If I run this on the ProductController I get true.

```
    public function show(Product $product)
    {
        dd($product->hasImage());

        return view('product.show', ['product' => $product]);
    }
```

**Comment by daniel-farina** [comment]
We can close this ticket. The problem was the incorrect model information in the database after implementing a custom Product model. 

Thank you!
