### ISSUE TITLE
how to add config for cart?

### ISSUE THREAD

**Issue by chepe263** [vanilophp/demo#5]
Reading the [documentation](https://vanilo.io/docs/0.3/cart) and [code](https://github.com/vanilophp/cart/blob/master/src/resources/config/module.php), there's a config setting `vanilo.cart.auto_destroy` and I would like to add it to my fork for this demo but I'm not sure how to add it.

Could you point me to the right direction?

**Comment by fulopattila122** [comment]
Add a new file `config/vanilo.php` with content:

```php
return [
    "cart" => [
         "auto_destroy" => true
    ]
]
```

Thanks for the catch! I'll add the file to this repo so that it's more straightforward.

**Comment by chepe263** [comment]
Is there a vendor:publish for this?

**Comment by fulopattila122** [comment]
No, there isn't.
