### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages."vanilo"

### ISSUE THREAD

**Issue by AJMALSARIM** [vanilophp/demo#56]
I'm getting this problem please help me.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework (locked at v8.14.0, required as ^8.12) -> satisfiable by laravel/framework[v8.14.0].
    - Installation request for vanilo/framework ^1.2 -> satisfiable by vanilo/framework[1.2.0, 1.2.1, 1.2.x-dev].
    - Can only install one of: laravel/framework[8.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.3, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.13.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.14.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.14.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.14.0].
    - Conclusion: install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework ^8.12 -> satisfiable by laravel/framework[8.x-dev, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.13.0, v8.14.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by fulopattila122** [comment]
Wow, thanks for the notification, it went unnoticed that the demo app for Vanilo 2.0 hasn't been finished and released :sweat_smile: 
Will do it shortly and ping back to this issue.

**Comment by fulopattila122** [comment]
Fixed in v2.0.0
