### ISSUE TITLE
Return value of Konekt\Concord\Proxies\EnumProxy::targetClass() must be of the type string, null returned

### ISSUE THREAD

**Issue by dipcb05** [vanilophp/demo#71]
I just installed some konekt module, i have no idea about enum proxy, but this error arises.
i checked  php artisan concord:enums. same error showing

**Comment by fulopattila122** [comment]
Does this help? vanilophp/product#12

**Comment by fulopattila122** [comment]
If not, please post the contents of `config/concord.php`

**Comment by dipcb05** [comment]
thanks for the reply. i have disconnected from the internet for some days. sorry for the late. 
here is my config/concord.php

`<?php

return [
    'modules' => [
        Konekt\AppShell\Providers\ModuleServiceProvider::class => [
            'ui' => [
                'name' => 'Vanilo',
                'url' => '/admin/product'
            ],
    'modules' => [
                Konekt\Customer\Providers\ModuleServiceProvider::class
            ],
    'modules' => [
                Konekt\Address\Providers\ModuleServiceProvider::class
            ]
        ], 
        Vanilo\Framework\Providers\ModuleServiceProvider::class => [
            'image' => [
                'variants' => [
                    'thumbnail' => [
                        'width'  => 250,
                        'height' => 188,
                        'fit' => 'fill'
                    ],
                    'medium' => [
                        'width'  => 540,
                        'height' => 406,
                        'fit' => 'fill'
                    ]
                ]
            ],
        ]
    ]
];`

**Comment by dipcb05** [comment]
the output of _php artisan concord:enums_

In EnumProxy.php line 33:
                                                                                                             
  Return value of Konekt\Concord\Proxies\EnumProxy::targetClass() must be of the type string, null returned

**Comment by fulopattila122** [comment]
@dipcb05 The config is wrong:

- the `modules` key is present 3 time --> it last one overrides the first 2.
- The customer and address module don't need to be added (they're included in AppShell)

The correct config is:

```php
// config/concord.php
<?php

return [
    'modules' => [
        Konekt\AppShell\Providers\ModuleServiceProvider::class => [
            'ui' => [
                'name' => 'Vanilo',
                'url' => '/admin/product'
            ]
        ],
        Vanilo\Framework\Providers\ModuleServiceProvider::class => [
            'image' => [
                'variants' => [
                    'thumbnail' => [
                        'width' => 250,
                        'height' => 188,
                        'fit' => 'fill'
                    ],
                    'medium' => [
                        'width' => 540,
                        'height' => 406,
                        'fit' => 'fill'
                    ]
                ]
            ],
        ]
    ]
];
```
